environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - gradlew.bat assemble testClasses --no-daemon

test_script:
  - gradlew.bat check --no-daemon

cache:
  - C:\Users\appveyor\.gradle
